wallets:
  - "MJKqp326RZCHnAAbew9MDdui3iCKWco7fsK9sVuZTX2"
  - "MJKqp326RZCHnAAbew9MDdui3iCKWco7fsK9sVuZTX2"
  - "48vcdkfm95LvngGxr2p8RVs3aeFv5p9hC6g8FsENR4go"
  - "GitYucwpNcg6Dx1Y15UQ9TQn8LZMX1uuqQNn8rXxEWNC"
  - "9QgXqrgdbVU8KcpfskqJpAXKzbaYQJecgMAruSWoXDkM"
  - "9uRJ5aGgeu2i3J98hsC5FDxd2PmRjVy9fQwNAy7fzLG3"
  - "EJRJswH9LyjhAfBWwPBvat1LQtrJYK4sVUzsea889cQt"
  - "EJRJswH9LyjhAfBWwPBvat1LQtrJYK4sVUzsea889cQt"
